// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/16/2026, 7:34:41 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/macbookair/Desktop/side-work/horse-trailers/admin-panel/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookair/Desktop/side-work/horse-trailers/admin-panel/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookair/Desktop/side-work/horse-trailers/admin-panel/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookair/Desktop/side-work/horse-trailers/admin-panel/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookair/Desktop/side-work/horse-trailers/admin-panel/plugins/**/*.{js,ts,mjs}","/Users/macbookair/Desktop/side-work/horse-trailers/admin-panel/composables/**/*.{js,ts,mjs}","/Users/macbookair/Desktop/side-work/horse-trailers/admin-panel/utils/**/*.{js,ts,mjs}","/Users/macbookair/Desktop/side-work/horse-trailers/admin-panel/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookair/Desktop/side-work/horse-trailers/admin-panel/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookair/Desktop/side-work/horse-trailers/admin-panel/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookair/Desktop/side-work/horse-trailers/admin-panel/app.config.{js,ts,mjs}","/Users/macbookair/Desktop/side-work/horse-trailers/admin-panel/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;